name: Build and Test Push

on:
  push:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Authenticate npm with the GPR
      uses: jgierer12/npm-auth-gpr@v1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn build
    - name: Run Tests
      run: yarn test
    - name: Run Code Coverage
      run: yarn test:coverage
    - name: Coveralls Code Coverage Report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
